/* Generated by Cython 0.23.4 */

#ifndef __PYX_HAVE__wrapper
#define __PYX_HAVE__wrapper


#ifndef __PYX_HAVE_API__wrapper

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(double) call_ker(PyObject *, std::pair<double,double> , std::pair<double,double> );
__PYX_EXTERN_C DL_IMPORT(double) call_wei(PyObject *, std::pair<double,double> );

#endif /* !__PYX_HAVE_API__wrapper */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initwrapper(void);
#else
PyMODINIT_FUNC PyInit_wrapper(void);
#endif

#endif /* !__PYX_HAVE__wrapper */
